CREATE TABLE IF NOT EXISTS "ΟΜΑΔΑ_ΣΧΟΛΕΙΟΥ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"ομαδα" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΚΑΤΗΓΟΡΙΑ_ΜΟΡΙΟΔΟΤΗΣΗΣ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"κατηγορια_μοριοδ" VARCHAR(1),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΕΙΔΟΣ_ΣΧΟΛΕΙΟΥ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"ειδος" VARCHAR(10),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΤΥΠΟΣ_ΣΧΟΛΕΙΟΥ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"τυπος" VARCHAR(70),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΚΩΔΙΚΟΣ_ΣΧΟΛΕΙΟΥ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"κωδικος" VARCHAR(10),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΣΧΟΛΕΙΑ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"ονομασια" VARCHAR(100),
	"ομαδα_id" INTEGER,
	"ειδος_id" INTEGER,
	"τυπος_id" INTEGER,
	"κωδικος_id" INTEGER,
	"τηλεφωνο" INTEGER,
	"fax" INTEGER,
	"email" VARCHAR(50),
	"δημος_id" INTEGER,
	"δημ_ενοτητα_id" INTEGER,
	"κοινοτητα_id" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΔΗΜΟΣ_ΣΧΟΛΕΙΟΥ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"δημος" VARCHAR(10),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΔΗΜΟΤΙΚΗ_ΕΝΟΤΗΤΑ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"δημ_ενοτητα" VARCHAR(20),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΚΟΙΝΟΤΗΤΑ_ΣΧΟΛΕΙΟΥ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"κοινοτητα" VARCHAR(20),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΕΚΠΑΙΔΕΥΤΙΚΟΙ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"ονομα" VARCHAR(25),
	"επωνυμο" VARCHAR(25),
	"πατρωνυμο" VARCHAR(25),
	"αμ" INTEGER,
	"αφμ" VARCHAR(12),
	"φυλο_id" INTEGER,
	"διευθυνση_κατ" VARCHAR(75),
	"τκ" INTEGER,
	"τηλεφωνο" INTEGER,
	"τηλεφωνο_κιν" INTEGER,
	"τηλεφωνο_2" INTEGER,
	"email" VARCHAR(50),
	"κατηγορια_μοριοδ_id" INTEGER,
	"ειδικοτητα_κωδ" VARCHAR(10),
	"ειδικοτητα_2_κωδ" VARCHAR(10),
	"περιοχη_μεταθ_id" INTEGER,
	"σχεση_εργ_id" INTEGER,
	"διευθυντης" VARCHAR(10),
	"υποδιευθυντης" VARCHAR(10),
	"υποχρ_ωραριο_υπηρ_φορεα" INTEGER,
	"μειωση_ωραριου" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΦΥΛΟ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"φυλο" VARCHAR(1),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΤΟΠΟΘΕΤΗΣΕΙΣ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"εκπαιδευτικος_id" INTEGER,
	"σχολειο_id" INTEGER,
	"ωραριο_id" INTEGER,
	"οργανο_αποφασης" VARCHAR(100),
	"οργανο_τοποθετ" VARCHAR(100),
	"αριθμ_πρωτοκ" VARCHAR(50),
	"αριθμ_πραξης" VARCHAR(50),
	"ημερ_πραξης" DATE,
	"αριθμ_πραξης_αναληψ" VARCHAR(50),
	"ημερ_αναληψης" DATE,
	"ημερ_αποφασης" DATE,
	"εναρξη_ισχυος" DATE,
	"ληξη_ισχυος" DATE,
	"αριθμ_πραξης_αποχωρ" VARCHAR(50),
	"ημερ_αποχωρ" DATE,
	"τελευτ_ενημερ" DATE,
	"σχεση_τοποθ_id" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΩΡΑΡΙΑ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"εκπαιδευτικος_id" INTEGER,
	"σχολειο_id" INTEGER,
	"αναθεση_α" INTEGER,
	"αναθεση_β" INTEGER,
	"αναθεση_3" INTEGER,
	"προσθ_τμημ" INTEGER,
	"αναθεση_αλλες" INTEGER,
	"συμπληρωση" INTEGER,
	"υπερωριες" INTEGER,
	"γραμματ_υποστ" INTEGER,
	"αναθεση_α_2η_ειδικ" INTEGER,
	"αναθεση_β_2η_ειδικ" INTEGER,
	"αναθεση_γ_2η_ειδικ" INTEGER,
	"συνδιδασκ_ημιωρο" VARCHAR(10),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΗΜΕΡΕΣ_ΕΡΓΑΣΙΑΣ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"μερα_id" INTEGER,
	"εκπαιδευτικος_id" INTEGER,
	"σχολειο_id" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΗΜΕΡΕΣ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"μερα" VARCHAR(20),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΕΙΔΙΚΟΤΗΤΕΣ" (
	"ειδικ_κωδικος" VARCHAR(10) NOT NULL UNIQUE,
	"ειδικοτητα" VARCHAR(50),
	PRIMARY KEY("ειδικ_κωδικος")
);


CREATE INDEX "ΕΙΔΙΚΟΤΗΤΕΣ_index_0"
ON "ΕΙΔΙΚΟΤΗΤΕΣ" ("ειδικ_κωδικος");

CREATE TABLE IF NOT EXISTS "ΠΕΡΙΟΧΕΣ_ΜΕΤΑΘΕΣΗΣ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"περιοχη_μεταθ" VARCHAR(50),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΣΧΕΣΗ_ΕΡΓΑΣΙΑΣ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"σχεση_εργ" VARCHAR(50),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ΣΧΕΣΕΙΣ_ΤΟΠΟΘΕΤΗΣΗΣ" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"σχεση_τοποθ" VARCHAR(100),
	PRIMARY KEY("id")
);



ALTER TABLE "ΣΧΟΛΕΙΑ"
ADD FOREIGN KEY("ομαδα_id") REFERENCES "ΟΜΑΔΑ_ΣΧΟΛΕΙΟΥ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΣΧΟΛΕΙΑ"
ADD FOREIGN KEY("ειδος_id") REFERENCES "ΕΙΔΟΣ_ΣΧΟΛΕΙΟΥ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΣΧΟΛΕΙΑ"
ADD FOREIGN KEY("τυπος_id") REFERENCES "ΤΥΠΟΣ_ΣΧΟΛΕΙΟΥ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΣΧΟΛΕΙΑ"
ADD FOREIGN KEY("κωδικος_id") REFERENCES "ΚΩΔΙΚΟΣ_ΣΧΟΛΕΙΟΥ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΣΧΟΛΕΙΑ"
ADD FOREIGN KEY("δημος_id") REFERENCES "ΔΗΜΟΣ_ΣΧΟΛΕΙΟΥ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΣΧΟΛΕΙΑ"
ADD FOREIGN KEY("δημ_ενοτητα_id") REFERENCES "ΔΗΜΟΤΙΚΗ_ΕΝΟΤΗΤΑ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΣΧΟΛΕΙΑ"
ADD FOREIGN KEY("κοινοτητα_id") REFERENCES "ΚΟΙΝΟΤΗΤΑ_ΣΧΟΛΕΙΟΥ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΕΚΠΑΙΔΕΥΤΙΚΟΙ"
ADD FOREIGN KEY("κατηγορια_μοριοδ_id") REFERENCES "ΚΑΤΗΓΟΡΙΑ_ΜΟΡΙΟΔΟΤΗΣΗΣ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΕΚΠΑΙΔΕΥΤΙΚΟΙ"
ADD FOREIGN KEY("φυλο_id") REFERENCES "ΦΥΛΟ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΗΜΕΡΕΣ_ΕΡΓΑΣΙΑΣ"
ADD FOREIGN KEY("μερα_id") REFERENCES "ΗΜΕΡΕΣ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΗΜΕΡΕΣ_ΕΡΓΑΣΙΑΣ"
ADD FOREIGN KEY("εκπαιδευτικος_id") REFERENCES "ΕΚΠΑΙΔΕΥΤΙΚΟΙ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΗΜΕΡΕΣ_ΕΡΓΑΣΙΑΣ"
ADD FOREIGN KEY("σχολειο_id") REFERENCES "ΣΧΟΛΕΙΑ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΕΚΠΑΙΔΕΥΤΙΚΟΙ"
ADD FOREIGN KEY("ειδικοτητα_κωδ") REFERENCES "ΕΙΔΙΚΟΤΗΤΕΣ"("ειδικ_κωδικος")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΕΚΠΑΙΔΕΥΤΙΚΟΙ"
ADD FOREIGN KEY("ειδικοτητα_2_κωδ") REFERENCES "ΕΙΔΙΚΟΤΗΤΕΣ"("ειδικ_κωδικος")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΕΚΠΑΙΔΕΥΤΙΚΟΙ"
ADD FOREIGN KEY("περιοχη_μεταθ_id") REFERENCES "ΠΕΡΙΟΧΕΣ_ΜΕΤΑΘΕΣΗΣ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΕΚΠΑΙΔΕΥΤΙΚΟΙ"
ADD FOREIGN KEY("σχεση_εργ_id") REFERENCES "ΣΧΕΣΗ_ΕΡΓΑΣΙΑΣ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΤΟΠΟΘΕΤΗΣΕΙΣ"
ADD FOREIGN KEY("εκπαιδευτικος_id") REFERENCES "ΕΚΠΑΙΔΕΥΤΙΚΟΙ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΤΟΠΟΘΕΤΗΣΕΙΣ"
ADD FOREIGN KEY("σχολειο_id") REFERENCES "ΣΧΟΛΕΙΑ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΤΟΠΟΘΕΤΗΣΕΙΣ"
ADD FOREIGN KEY("ωραριο_id") REFERENCES "ΩΡΑΡΙΑ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΩΡΑΡΙΑ"
ADD FOREIGN KEY("εκπαιδευτικος_id") REFERENCES "ΕΚΠΑΙΔΕΥΤΙΚΟΙ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΩΡΑΡΙΑ"
ADD FOREIGN KEY("σχολειο_id") REFERENCES "ΣΧΟΛΕΙΑ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ΤΟΠΟΘΕΤΗΣΕΙΣ"
ADD FOREIGN KEY("σχεση_τοποθ_id") REFERENCES "ΣΧΕΣΕΙΣ_ΤΟΠΟΘΕΤΗΣΗΣ"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

INSERT INTO TABLE "ΤΥΠΟΣ_ΣΧΟΛΕΙΟΥ"("τυπος")
VALUES
	("Ημερήσιο Γυμνάσιο"),
	("Ωνάσειο (ΔΗΜ.Ω.Σ.) Γυμνάσιο"),
	("Εσπερινό Γυμνάσιο με Λυκειακές Τάξεις"),
	("Μουσικό Γυμνάσιο με Μουσικές Λυκειακές Τάξεις"),
	("Ημερήσιο Γυμνάσιο με Λυκειακές Τάξεις"),
	("Γυμνάσιο Διαπολιτισμικής Εκπαίδευσης με Λυκειακές Τάξεις"),
	("Ενιαίο Ειδικό Επαγγελματικό Γυμνάσιο - Λύκειο"),
	("Καλλιτεχνικό Γυμνάσιο με Λυκειακές Τάξεις"),
	("Ημερήσιο ΕΠΑΛ"),
	("ΕΕΕΕΚ"),
	("Πρότυπο ΕΠΑΛ"),
	("Εσπερινό ΕΠΑΛ"),
	("Ημερήσιο Γενικό Λύκειο"),
	("Ωνάσειο (ΔΗΜ.Ω.Σ.) Λύκειο"),
	("ΣΕΚ");

INSERT INTO TABLE "ΔΗΜΟΣ_ΣΧΟΛΕΙΟΥ" ("δημος")
VALUES 
	("ΒΟΪΟΥ"),
	("ΚΟΖΑΝΗΣ"),
	("ΕΟΡΔΑΙΑΣ"),
	("ΣΕΡΒΙΩΝ"),
	("ΒΕΛΒΕΝΤΟΥ");

INSERT INTO TABLE "ΔΗΜΟΤΙΚΗ_ΕΝΟΤΗΤΑ" ("δημ_ενοτητα")
VALUES 
	("ΑΣΚΙΟΥ"),
	("ΚΟΖΑΝΗΣ"),
	("ΝΕΑΠΟΛΗΣ"),
	("ΠΤΟΛΕΜΑΪΔΑΣ"),
	("ΣΕΡΒΙΩΝ"),
	("ΚΑΜΒΟΥΝΙΩΝ"),
	("ΣΙΑΤΙΣΤΑΣ"),
	("ΤΣΟΤΥΛΙΟΥ"),
	("ΒΕΛΒΕΝΤΟΥ"),
	("ΠΕΝΤΑΛΟΦΟΥ"),
	("ΜΟΥΡΙΚΙΟΥ"),
	("ΒΕΡΜΙΟΥ"),
	("ΑΙΑΝΗΣ"),
	("ΕΛΛΗΣΠΟΝΤΟΥ"),
	("ΛΙΒΑΔΕΡΟΥ"),
	("ΕΛΙΜΕΙΑΣ");

INSERT INTO TABLE "ΚΟΙΝΟΤΗΤΑ_ΣΧΟΛΕΙΟΥ" ("κοινοτητα") 
VALUES 
	("ΕΡΑΤΥΡΑΣ"),
	("ΚΟΖΑΝΗΣ"),
	("ΞΗΡΟΛΙΜΝΗΣ"),
	("ΝΕΑΠΟΛΗΣ"),
	("ΠΤΟΛΕΜΑΪΔΟΣ"),
	("ΣΕΡΒΙΩΝ"),
	("ΤΡΑΝΟΒΑΛΤΟΥ"),
	("ΣΙΑΤΙΣΤΗΣ"),
	("ΓΑΛΑΤΙΝΗΣ"),
	("ΤΣΟΤΙΛΙΟΥ"),
	("ΒΕΛΒΕΝΤΟΥ"),
	("ΠΕΝΤΑΛΟΦΟΥ"),
	("ΕΜΠΟΡΙΟΥ"),
	("ΑΝΑΤΟΛΙΚΟΥ"),
	("ΑΙΑΝΗΣ"),
	("ΚΑΠΝΟΧΩΡΙΟΥ"),
	("ΛΙΒΑΔΕΡΟΥ"),
	("ΚΡΟΚΟΥ"),
	("ΛΕΥΚΟΠΗΓΗΣ"),
	("ΠΕΡΔΙΚΚΑ"),
	("ΠΕΝΤΑΒΡΥΣΟΥ");

INSERT INTO TABLE "ΦΥΛΟ" ("φυλο")
VALUES 
	("Θ"),
	("Α");

INSERT INTO TABLE "ΕΙΔΙΚΟΤΗΤΕΣ" ("ειδικ_κωδικος","ειδικοτητα")
VALUES 
	("ΠΕ01,ΘΕΟΛΟΓΟΙ")
	("ΠΕ02,ΦΙΛΟΛΟΓΟΙ")
	("ΠΕ03,ΜΑΘΗΜΑΤΙΚΟΙ")
	("ΠΕ04.01,ΦΥΣΙΚΟΙ")
	("ΠΕ04.02,ΧΗΜΙΚΟΙ")
	("ΠΕ.04.04,ΒΙΟΛΟΓΟΙ")
	("ΠΕ04.05,ΓΕΩΛΟΓΟΙ")
	("ΠΕ05,ΓΑΛΛΙΚΗΣ")
	("ΠΕ06,ΑΓΓΛΙΚΗΣ")
	("ΠΕ07,ΓΕΡΜΑΝΙΚΗΣ")
	("ΠΕ08,ΚΑΛΛΙΤΕΧΝΙΚΩΝ")
	("ΠΕ11,ΦΥΣΙΚΗΣ ΑΓΩΓΗΣ")
	("ΠΕ33,Μεθοδολ.Ιστορ")
	("ΠΕ34,ΙΤΑΛΙΚΗΣ")
	("ΠΕ40,ΙΣΠΑΝΙΚΗΣ")
	("ΠΕ78,ΚΟΙΝ ΕΠΙΣΤΗΜΩΝ")
	("ΠΕ79,ΜΟΥΣΙΚΗΣ")
	("ΠΕ79.02,ΤΕΧΝΟΛ.ΜΟΥΣ.")
	("ΠΕ80,ΟΙΚΟΝΟΜΙΑΣ")
	("ΠΕ81,ΠΟΛ. ΜΗΧ-ΑΡΧΙΤΕΚΤ")
	("ΠΕ82,ΜΗΧΑΝΟΛΟΓΩΝ")
	("ΠΕ83,ΗΛΕΚΤΡΟΛΟΓΩΝ")
	("ΠΕ84,ΗΛΕΚΤΡΟΝΙΚΩΝ")
	("ΠΕ85,ΧΗΜΙΚΩΝ ΜΗΧΑΝΙΚΩΝ")
	("ΠΕ86,ΠΛΗΡΟΦΟΡΙΚΗΣ")
	("ΠΕ87.01,ΙΑΤΡΙΚΗΣ")
	("ΠΕ87.02,ΝΟΣΗΛΕΥΤΙΚΗΣ")
	("ΠΕ87.03,ΑΙΣΘΗΤΙΚΗΣ")
	("ΠΕ87.04,ΙΑΤΡ. ΕΡΓΑΣ.")
	("ΠΕ87.05,ΟΔΟΝΤΟΤΕΧΝΙΚΗΣ")
	("ΠΕ87.06,ΚΟΙΝ. ΕΡΓΑΣΙΑΣ")
	("ΠΕ87.07,ΡΑΔΙΟΛΟΓΙΑΣ")
	("ΠΕ87.08,ΦΥΣΙΟΘΕΡΑΠΕΙΑΣ")
	("ΠΕ87.09,ΒΡΕΦΟΝΗΠΙΟΚΟΜΩΝ")
	("ΠΕ87.10,ΔΗΜΟΣΙΑΣ ΥΓΙΕΙΝΗΣ")
	("ΠΕ88.01,ΓΕΩΠΟΝΟΙ")
	("ΠΕ88.02,ΦΥΤ.ΠΑΡΑΓΩΓΗΣ")
	("ΠΕ88.03,ΖΩΪΚΗΣ ΠΑΡΑΓΩΓΗΣ")
	("ΠΕ88.04,ΔΙΑΤΡΟΦΗΣ")
	("ΠΕ88.05,ΦΥΣΙΚΟΥ ΠΕΡΙΒΑΛΛΟΝΤΟΣ")
	("ΠΕ89.01,ΚΑΛΛΙΤΕΧΝ. ΣΠΟΥΔΩΝ")
	("ΠΕ89.02,ΣΧΕΔΙΑΣΜΟΥ &ΠΑΡΑΓ.")
	("ΠΕ90,ΝΑΥΤΙΚΩΝ")
	("ΠΕ91.01,ΘΕΑΤΡΙΚΩΝ ΣΠΟΥΔΩΝ")
	("ΠΕ91.02,ΔΡΑΜΑΤΙΚΗΣ ΤΕΧΝΗΣ")
	("ΤΕ 01.04,ΨΥΚΤΙΚΟΙ")
	("ΤΕ01.06,ΗΛΕΚΤΡΟΛΟΓΟΙ")
	("ΤΕ01.07,ΗΛΕΚΤΡΟΝΙΚΟΙ")
	("ΤΕ01.13,ΠΡΟΓΡΑΜΜ. Η/Υ")
	("ΤΕ01.19,ΚΟΜΜΩΤΙΚΗΣ")
	("ΤΕ01.20,ΑΙΣΘΗΤΙΚΗΣ")
	("ΤΕ01.25,ΑΡΓΥΡΟΧΡΥΣΟΧΟΪΑΣ")
	("ΤΕ01.26,ΟΔΟΝΤΟΤΕΧΝΙΚΗΣ")
	("ΤΕ01.29,ΒΟΗΘΩΝ ΙΑΤΡ. ΒΙΟΛ.")
	("ΤΕ01.30,ΒΟΗΘΟΙ ΒΡΕΦΟΚΟΜΩΝ")
	("ΤΕ01.31,ΧΕΙΡΙΣΤΕΣ ΙΑΤΡΙΚΩΝ ΣΥΣΚ")
	("ΤΕ02.01,ΣΧΕΔΙΑΣΤΕΣ-ΔΟΜΙΚΟΙ")
	("ΤΕ02.02,ΜΗΧΑΝΟΛΟΓΟΙ")
	("ΤΕ02.03,ΧΗΜΙΚΟΙ ΕΡΓΑΣΤΗΡΙΩΝ")
	("ΤΕ02.04,ΟΙΚΟΝΟΜΙΑΣ-ΔΙΟΙΚΗΣΗΣ")
	("ΤΕ02.05,ΕΦΑΡΜΟΣΜΕΝΩΝ ΤΕΧΝΩΝ")
	("ΤΕ02.06,ΣΧΕΔΙΑΣΜΟΥ &ΠΑΡΑΓ.")
	("ΤΕ02.07,ΓΕΩΠΟΝΙΑΣ")
	("ΠΕ41,ΘΕΩΡΙΑΣ/ΙΣΤΟΡΙΑΣ ΤΕΧΝΗΣ");

INSERT INTO TABLE "ΠΕΡΙΟΧΕΣ_ΜΕΤΑΘΕΣΗΣ" ("περιοχη_μεταθ")
VALUES
	("ΗΜΑΘΙΑΣ (Δ.Ε.) 2018"),
	("ΚΟΖΑΝΗΣ (Δ.Ε.) 2018"),
	("ΖΑΚΥΝΘΟΥ (Δ.Ε.) 2018"),
	("ΦΘΙΩΤΙΔΑΣ (Δ.Ε.) 2018"),
	("Α΄ ΚΕΦΑΛΛΗΝΙΑΣ (Δ.Ε.) 2018"),
	("Α΄ ΚΕΡΚΥΡΑΣ (Δ.Ε.) 2018"),
	("ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ (Δ.Ε.) 2018"),
	("ΧΑΝΙΩΝ (Δ.Ε.) 2018"),
	("ΚΑΣΤΟΡΙΑΣ (Δ.Ε.) 2018"),
	("Α΄ ΠΕΙΡΑΙΑ (Δ.Ε.) 2018"),
	("ΦΛΩΡΙΝΑΣ (Δ.Ε.) 2018"),
	("Β΄ ΔΩΔΕΚΑΝΗΣΟΥ (Δ.Ε.) 2018"),
	("ΛΑΣΙΘΙΟΥ (Δ.Ε.) 2018"),
	("Α΄ ΘΕΣΣΑΛΟΝΙΚΗΣ (Δ.Ε.) 2018"),
	("Α΄ ΑΘΗΝΑΣ (Δ.Ε.) 2018"),
	("ΛΕΥΚΑΔΑΣ (Δ.Ε.) 2018"),
	("Α΄ ΚΑΒΑΛΑΣ (Δ.Ε.) 2018"),
	("ΚΟΡΙΝΘΙΑΣ (Δ.Ε.) 2018"),
	("ΓΡΕΒΕΝΩΝ (Δ.Ε.) 2018"),
	("ΠΙΕΡΙΑΣ (Δ.Ε.) 2018"),
	("ΠΕΛΛΑΣ (Δ.Ε.) 2018"),
	("Δ΄ ΚΥΚΛΑΔΩΝ (Δ.Ε.) 2018"),
	("Α΄ ΕΥΒΟΙΑΣ (Δ.Ε.) 2018"),
	("ΧΑΛΚΙΔΙΚΗΣ (Δ.Ε.) 2018"),
	("Α΄ ΛΕΣΒΟΥ (Δ.Ε.) 2018"),
	("ΗΡΑΚΛΕΙΟΥ (Δ.Ε.) 2018"),
	("Β΄ ΚΑΒΑΛΑΣ (Δ.Ε.) 2018"),
	("ΒΟΙΩΤΙΑΣ (Δ.Ε.) 2018"),
	("Α΄ ΔΩΔΕΚΑΝΗΣΟΥ (Δ.Ε.) 2018"),
	("ΛΑΚΩΝΙΑΣ (Δ.Ε.) 2018"),
	("ΑΡΤΑΣ (Δ.Ε.) 2018"),
	("Β΄ ΘΕΣΣΑΛΟΝΙΚΗΣ (Δ.Ε.) 2018"),
	("ΚΟΖΑΝΗΣ (Π.Ε.) 2018"),
	("ΑΡΚΑΔΙΑΣ (Δ.Ε.) 2018"),
	("Δ΄ ΑΘΗΝΑΣ (Δ.Ε.) 2018"),
	("Α΄ ΜΑΓΝΗΣΙΑΣ (Δ.Ε.) 2018"),
	("ΤΡΙΚΑΛΩΝ (Δ.Ε.) 2018"),
	("Α΄ ΚΥΚΛΑΔΩΝ (Δ.Ε.) 2018"),
	("ΜΕΣΣΗΝΙΑΣ (Δ.Ε.) 2018")
	("ΦΩΚΙΔΑΣ (Δ.Ε.) 2018"),
	("ΗΜΑΘΙΑΣ (Π.Ε.) 2018"),
	("ΘΕΣΠΡΩΤΙΑΣ (Δ.Ε.) 2018"),
	("Β΄ ΜΑΓΝΗΣΙΑΣ (Δ.Ε.) 2018"),
	("ΔΥΤ. ΑΤΤΙΚΗΣ (Δ.Ε.) 2018"),
	("Β΄ ΚΥΚΛΑΔΩΝ (Δ.Ε.) 2018"),
	("ΠΡΕΒΕΖΑΣ (Δ.Ε.) 2018");

INSERT INTO TABLE "ΠΕΡΙΟΧΕΣ_ΜΕΤΑΘΕΣΗΣ" ("περιοχη_μεταθ")
VALUES
	("Μόνιμος"),
	("Αναπληρωτής"),
	("Αναπληρωτής Παράλληλης Στήριξης μέσω ΕΣΠΑ"),
	("Αναπληρωτής μέσω ΕΣΠΑ"),
	("Αναπληρωτής Ειδικής μέσω ΕΣΠΑ"),
	("Αναπληρωτής Μειωμένου Ωραρίου"),
	("Αναπληρωτής ΣΔΕΥ μέσω ΕΣΠΑ"),
	("Αναπληρωτής Μειωμένου Ωραρίου μέσω ΕΣΠΑ"),
	("Αναπληρωτής ΜΝΑΕ μέσω ΕΣΠΑ");

INSERT INTO TABLE "ΣΧΕΣΕΙΣ_ΤΟΠΟΘΕΤΗΣΗΣ" ("σχεση_τοποθ")
VALUES
	("Μερική Διάθεση (Συμπλήρωση Ωραρίου)"),
	("Ολική Διάθεση (ανάγκες υπηρεσίας - κύριος φορέας)"),
	("Οργανικά από Αρση Υπεραριθμίας"),
	("Επί Θητεία"),
	("Οργανικά"),
	("Απόσπαση (με αίτηση - κύριος φορέας)"),
	("Από Διάθεση ΠΥΣΠΕ/ΠΥΣΔΕ"),
	("Οργανικά σε Τμήμα Ένταξης"),
	("Οργανικά από Αμοιβαία Μετάθεση");

INSERT INTO TABLE "ΟΜΑΔΑ_ΣΧΟΛΕΙΟΥ" ("ομαδα")
VALUES
	("3"),
	("1"),
	("2"),
	("4");

INSERT INTO TABLE "ΚΑΤΗΓΟΡΙΑ_ΜΟΡΙΟΔΟΤΗΣΗΣ" ("κατηγορια_μοριοδ")
VALUES
	("Ζ"),
	("Α"),
	("Γ"),
	("Δ"),
	("Η"),
	("Ε"),
	("ΙΒ"),
	("Θ"),
	("Β");

INSERT INTO TABLE "ΕΙΔΟΣ_ΣΧΟΛΕΙΟΥ" ("ειδος")
VALUES
("Γυμνάσια"),
("Επαγγελματικά Λύκεια"),
("Ειδικής Επαγγελματικής Εκπαίδευσης και Κατάρτισης"),
("Λύκεια"),
("Σχολικό Εργαστηριακό Κέντρο");

INSERT INTO TABLE "ΗΜΕΡΕΣ" ("μερα")
VALUES
("Δευτέρα"),
("Τρίτη"),
("Τετάρτη"),
("Πέμπτη"),
("Παρασκευή");


INSERT INTO TABLE "ΚΩΔΙΚΟΣ_ΣΧΟΛΕΙΟΥ" ("κωδικος")
VALUES
	("=""2701000"""),
	("=""2701010"""),
	("=""2701011"""),
	("=""2701020"""),
	("=""2701021"""),
	("=""2701022"""),
	("=""2701025"""),
	("=""2701026"""),
	("=""2701030"""),
	("=""2701040"""),
	("=""2703010"""),
	("=""2704010"""),
	("=""2704011"""),
	("=""2704020"""),
	("=""2704021"""),
	("=""2704022"""),
	("=""2704025"""),
	("=""2705010"""),
	("=""2705030"""),
	("=""2706010"""),
	("=""2706015"""),
	("=""2706020"""),
	("=""2707010"""),
	("=""2708010"""),
	("=""2709010"""),
	("=""2710010"""),
	("=""2710030"""),
	("=""2711001"""),
	("=""2711201"""),
	("=""2712010"""),
	("=""2713010"""),
	("=""2714010"""),
	("=""2718010"""),
	("=""2719010"""),
	("=""2720010"""),
	("=""2740002"""),
	("=""2740070"""),
	("=""2740080"""),
	("=""2740090"""),
	("=""2740101"""),
	("=""2740105"""),
	("=""2741001"""),
	("=""2741002"""),
	("=""2748000"""),
	("=""2750081"""),
	("=""2750110"""),
	("=""2751009"""),
	("=""2751010"""),
	("=""2751011"""),
	("=""2751020"""),
	("=""2751022"""),
	("=""2753010"""),
	("=""2754010"""),
	("=""2754011"""),
	("=""2755010"""),
	("=""2756010"""),
	("=""2758010"""),
	("=""SEK044"""),
	("=""SEK111""");

